title: Fathin Afif # your name (or website title) here
logo: "images\fathin-profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Fresh Graduate in Industrial Engineering, equipped with the ability to quickly adjust to new environments, and have proven history of effectively gathering, managing, and structuring data to facilitate precise decision-making. I have expertise in multiple data analysis software including SQL, Excel, Tableau, and Python. Along with excellent communication, organizational, and analytical capabilities.
  <br><br>
  Recently clearing Google Data Analytics Certificate.
  <br><br>
  <a href="https://www.linkedin.com/in/fathin-afif/">View my LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
