title: Fathin Afif # your name (or website title) here
logo: "images/fathin-profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Industrial Engineering graduate with skills to assist businesses in making data-driven decisions. Expertise in SQL, Excel, Tableau, Power BI, Looker Studio, and Python. With a proven track record of providing actionable insights and driving data-driven decision-making, I have experience as a Project-Based Big Data Analytics intern at Kimia Farma and as a Quality Control Analyst intern at PT Bugak Palma Sejahtera.
  <br><br>
  Recently clearing Google Data Analytics Certificate.
  <br><br>
  <a href="https://www.linkedin.com/in/fathin-afif/">View my LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
